# Generated by Django 3.1.2 on 2020-11-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
