# Generated by Django 3.1.2 on 2020-10-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('enabled', 'enabled'), ('disable', 'disable'), ('delete', 'delete')], default='ENABLED', max_length=25)),
                ('name', models.CharField(max_length=101)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
