# Generated by Django 3.1.2 on 2020-11-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_auto_20201117_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='status',
            field=models.CharField(choices=[('enabled', 'enabled'), ('disable', 'disable'), ('delete', 'delete'), ('edited', 'edited')], default='enabled', max_length=25),
        ),
    ]
