# Generated by Django 3.1.2 on 2021-01-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0004_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='comment_len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dream',
            name='dislike_len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dream',
            name='like_len',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
