# Generated by Django 3.1.2 on 2021-04-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0007_auto_20210416_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('enabled', 'enabled'), ('disable', 'disable'), ('delete', 'delete'), ('edited', 'edited')], default='enabled', max_length=25),
        ),
    ]
